### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by tamer-shamseldin** [Isilon/isilon_hadoop_tools#116]
OneFS-95-1# isi upgrade patches list
Patch Name                             Description                         Status
------------------------------------------------------------------------------------
9.5.0.6_LTS2023_GA-RUP_PSP-3839        Multiple Userspace and Kernel Fixes Installed
9.5.0_UGA-PATCH-INFRA_2023-03_PSP-3206 Patch Framework Fix                 Installed
------------------------------------------------------------------------------------
Total: 2

OneFS-95-1# ./iht/bin/isilon_create_users --no-verify --onefs-user "root" --zone "Prod-CDH" --dist "cdp" "192.168.20.5"
Traceback (most recent call last):
  File "./iht/bin/isilon_create_users", line 5, in <module>
    from isilon_hadoop_tools._scripts import isilon_create_users
  File "/root/iht/lib/python3.8/site-packages/isilon_hadoop_tools/_scripts.py", line 8, in <module>
    import urllib3
  File "/root/iht/lib/python3.8/site-packages/urllib3/__init__.py", line 41, in <module>
    raise ImportError(
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2zh-fips  30 May 2023'. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by nickyruggs** [comment]
Same here... Centos 7 & Python3.8

**Comment by tucked** [comment]
This likely isn't something IHT should address directly (because the fix would be to block the newer, more secure urllib3 v2, even though IHT should otherwise be able to run with it).

IHT _is_ still fine with urllib3 v1, though:
https://github.com/Isilon/isilon_hadoop_tools/blob/cc9488d5152f15edcc875aada03c2149c1a14cf3/setup.py#L32

So I think you should be able to work around by running this inside the virtualenv where IHT is installed:
``` sh
pip install 'urllib3 < 2'
```

If you installed with `pipx`, you can `inject` that command:
``` sh
pipx inject isilon-hadoop-tools 'urllib3 < 2'
```

The better solution, however, is probably to upgrade OpenSSL.

**Comment by nickyruggs** [comment]
That 'inject' worked just fine.  Thanks.
