### ISSUE TITLE
Restarted after failure crashes

### ISSUE THREAD

**Issue by nickyruggs** [Isilon/isilon_hadoop_tools#118]
After the failure with the proxyusers privilege, restarting the script failed at the end...
``` console
[INFO] Creating the HTTP proxy user with the following members: cloudera-scm (user)...
[INFO] Flushing the auth cache...
Exception ignored in: <function ApiClient.__del__ at 0x7f00c29eedc0>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/isilon-hadoop-tools/lib/python3.8/site-packages/isi_sdk_8_2_2/api_client.py", line 89, in __del__
    self.pool.close()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f00c29eedc0>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/isilon-hadoop-tools/lib/python3.8/site-packages/isi_sdk_8_2_2/api_client.py", line 89, in __del__
    self.pool.close()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f00c29eedc0>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/isilon-hadoop-tools/lib/python3.8/site-packages/isi_sdk_8_2_2/api_client.py", line 89, in __del__
    self.pool.close()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f00c29eedc0>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/isilon-hadoop-tools/lib/python3.8/site-packages/isi_sdk_8_2_2/api_client.py", line 89, in __del__
    self.pool.close()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f00c29eedc0>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/isilon-hadoop-tools/lib/python3.8/site-packages/isi_sdk_8_2_2/api_client.py", line 89, in __del__
    self.pool.close()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
[root@cdp-demo-m ~]# 
```

**Comment by tucked** [comment]
This has been raised internally before:
> this is a known issue multiproccesing.pool() python library , no work required on SDK front .

AFAIK it's innocuous and has not been seen on Python 3.9+
